### PR TITLE
Added fsm.cpp and fsm.h for the finite state machine implementation

### PR DESCRIPTION
**Pull request by DiegoRadigues**
This Pull Request adds the following files related to the Finite State Machine (FSM) implementation:

fsm.cpp: Implements the core logic of the FSM, including state transitions and associated actions.
fsm.h: Declares the FSM's structure, constants, and function prototypes to facilitate integration into other project components.

### CODE REVIEW

**Comment by edw-crtn** [comment]
The variable directionChanges is clear, but maybe a short comment explaining it counts only after the first start could help.

**Comment by edw-crtn** [comment]
What if the system receives a detection signal while in STATE_STOPPED? Good that we return immediately; maybe we should log a debug message?

**Comment by Prota0202** [comment]
Could we add more comments on the state transitions? It might help new contributors understand why we switch from IDLE to RUNNING_CW after the first detection.

**Comment by DiegoRadigues** [comment]
> Could we add more comments on the state transitions? It might help new contributors understand why we switch from IDLE to RUNNING_CW after the first detection.

@Prota0202 Thanks for the input, but I believe the current level of commenting is sufficient. The state transitions are already straightforward, and adding more comments would be redundant.

**Pull request merged**
